language: node_js
node_js:
- "10.13"

env:
- SLS_DEBUG=* TWITTER_SCREEN_NAME=this_vid EXTERNAL_URL=http://hamelha.com/ TWITTER_CALLBACK_URL="https://thisvid.space/_/completetwittersignin"

cache:
  directories:
  - node_modules

install: npm i && npm i -g serverless

stages:
- name: predeploy
- name: deploy
  if: branch = master

jobs:
  include:
  - stage: deploy
    before_script:
      - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      - unzip awscli-bundle.zip
      - ./awscli-bundle/install -b ~/bin/aws
      - export PATH=~/bin:$PATH
    script: |
      aws --region us-east-1 s3 cp \
      s3://shalvah-creds/downloadthisvideo-serviceaccount.json  \
      ./downloadthisvideo-serviceaccount.json && \
      sls deploy

  - stage: predeploy
    name: Test
    script: npm run test

  - stage: predeploy
    name: Lint
    script: npm run lint
